apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: insights-operator-gather
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
  - apiGroups:
      - imageregistry.operator.openshift.io
    resources:
      - configs
      - imagepruners
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - proxy
  - apiGroups:
      - ""
    resources:
      - nodes/log
      - nodes/metrics
      - nodes/proxy
      - nodes/stats
    verbs:
      - get
  - apiGroups:
      - config.openshift.io
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - machine.openshift.io
    resources:
      - machinesets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - operator.openshift.io
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - installers.datahub.sap.com
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - operators.coreos.com
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
