apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-dns-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-dns-operator
subjects:
  - kind: ServiceAccount
    name: dns-operator
    namespace: openshift-dns-operator
