apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.opgroup.permissions/aggregate-to-e43efcaa45c9f8d0-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: elasticsearches.logging.openshift.io-v1-edit
rules:
  - apiGroups:
      - logging.openshift.io
    resources:
      - elasticsearches
    verbs:
      - create
      - update
      - patch
      - delete
