apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  name: system:openshift:cloud-credential-operator:cluster-reader
rules:
  - apiGroups:
      - cloudcredential.openshift.io
    resources:
      - credentialsrequests
    verbs:
      - get
      - list
      - watch
