apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-samples-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-samples-operator
subjects:
  - kind: ServiceAccount
    name: cluster-samples-operator
    namespace: openshift-cluster-samples-operator
