apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-ingress-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
      - serviceaccounts
      - endpoints
      - services
      - secrets
      - pods
      - events
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - create
      - get
      - list
      - watch
      - update
  - apiGroups:
      - operator.openshift.io
    resources:
      - ingresscontrollers
      - ingresscontrollers/status
    verbs:
      - '*'
  - apiGroups:
      - ingress.operator.openshift.io
    resources:
      - dnsrecords
      - dnsrecords/status
    verbs:
      - '*'
  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
      - ingresses
      - dnses
      - apiservers
      - networks
    verbs:
      - get
  - apiGroups:
      - config.openshift.io
    resources:
      - dnses
      - infrastructures
      - ingresses
    verbs:
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators
    verbs:
      - create
      - get
  - apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators/status
    verbs:
      - update
  - apiGroups:
      - route.openshift.io
    resources:
      - routers/metrics
    verbs:
      - get
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - list
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes/status
    verbs:
      - update
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - hostnetwork
    resources:
      - securitycontextconstraints
    verbs:
      - use
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
