apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-node-tuning:tuned
rules:
  - apiGroups:
      - tuned.openshift.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
