apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.opgroup.permissions/aggregate-to-e43efcaa45c9f8d0-view: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: elasticsearches.logging.openshift.io-v1-crdview
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - elasticsearches.logging.openshift.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
