apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.opgroup.permissions/aggregate-to-1b4d744dedc664d9-view: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: clusterlogforwarders.logging.openshift.io-v1-crdview
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - clusterlogforwarders.logging.openshift.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
