apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-extensions-reader
rules:
  - apiGroups:
      - console.openshift.io
    resources:
      - consolelinks
      - consolenotifications
      - consoleexternalloglinks
      - consoleclidownloads
      - consoleyamlsamples
    verbs:
      - get
      - list
      - watch
