apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.owner: clusterlogging.4.6.0-202106010807.p0.git.e091c13
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-logging
    operators.coreos.com/cluster-logging.openshift-logging: ""
  name: clusterlogging.4.6.0-202106010807.p0.git.e091c13-685f78498c
rules:
  - apiGroups:
      - console.openshift.io
    resources:
      - consoleexternalloglinks
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - '*'
  - apiGroups:
      - oauth.openshift.io
    resources:
      - oauthclients
    verbs:
      - '*'
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - '*'
  - apiGroups:
      - config.openshift.io
    resources:
      - proxies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - services
      - services/finalizers
    verbs:
      - get
      - list
      - watch
