apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.opgroup.permissions/aggregate-to-1b4d744dedc664d9-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: clusterlogforwarders.logging.openshift.io-v1-edit
rules:
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterlogforwarders
    verbs:
      - create
      - update
      - patch
      - delete
