aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        olm.opgroup.permissions/aggregate-to-4bca9f23e412d79d-admin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.owner: olm-operators
    olm.owner.kind: OperatorGroup
    olm.owner.namespace: openshift-operator-lifecycle-manager
  name: olm-operators-admin
rules:
  - apiGroups:
      - packages.operators.coreos.com
    resources:
      - packagemanifests
    verbs:
      - '*'
