apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: system:openshift:operator:kube-apiserver-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kube-apiserver-operator
    namespace: openshift-kube-apiserver-operator
