aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        olm.opgroup.permissions/aggregate-to-398cc1f7861443fe-view: "true"
    - matchLabels:
        olm.opgroup.permissions/aggregate-to-1b4d744dedc664d9-view: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.owner: openshift-logging-6hbn8
    olm.owner.kind: OperatorGroup
    olm.owner.namespace: openshift-logging
  name: openshift-logging-6hbn8-view
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - clusterloggings.logging.openshift.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterloggings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - clusterlogforwarders.logging.openshift.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterlogforwarders
    verbs:
      - get
      - list
      - watch
