aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        olm.opgroup.permissions/aggregate-to-e43efcaa45c9f8d0-view: "true"
    - matchLabels:
        olm.opgroup.permissions/aggregate-to-9337dac30a6def29-view: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.owner: openshift-operators-redhat-mgp7x
    olm.owner.kind: OperatorGroup
    olm.owner.namespace: openshift-operators-redhat
  name: openshift-operators-redhat-mgp7x-view
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - elasticsearches.logging.openshift.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - logging.openshift.io
    resources:
      - elasticsearches
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - kibanas.logging.openshift.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - logging.openshift.io
    resources:
      - kibanas
    verbs:
      - get
      - list
      - watch
