apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-monitoring-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-operator
subjects:
  - kind: ServiceAccount
    name: cluster-monitoring-operator
    namespace: openshift-monitoring
