apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.owner: elasticsearch-operator.4.6.0-202106010807.p0.git.c07c7ab
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-operators-redhat
    operators.coreos.com/elasticsearch-operator.openshift-operators-redhat: ""
  name: elasticsearch-operator.4.6.0-202106010807.p0.git.c07c7-bcffc569
rules:
  - apiGroups:
      - console.openshift.io
    resources:
      - consolelinks
      - consoleexternalloglinks
    verbs:
      - get
      - create
      - update
      - delete
  - apiGroups:
      - logging.openshift.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
      - services/finalizers
    verbs:
      - '*'
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
      - servicemonitors
    verbs:
      - '*'
  - apiGroups:
      - oauth.openshift.io
    resources:
      - oauthclients
    verbs:
      - '*'
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - '*'
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - '*'
  - apiGroups:
      - config.openshift.io
    resources:
      - proxies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resourceNames:
      - elasticsearch-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - delete
