apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: aggregate-olm-edit
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
      - catalogsources
      - installplans
      - subscriptions
    verbs:
      - delete
