apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.opgroup.permissions/aggregate-to-398cc1f7861443fe-view: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: clusterloggings.logging.openshift.io-v1-crdview
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - clusterloggings.logging.openshift.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
