apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-config-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: machine-config-server
subjects:
  - kind: ServiceAccount
    name: machine-config-server
    namespace: openshift-machine-config-operator
