aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-view: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: view
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
      - catalogsources
      - installplans
      - subscriptions
      - operatorgroups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - packages.operators.coreos.com
    resources:
      - packagemanifests
      - packagemanifests/icon
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - clusterlogforwarders.logging.openshift.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterlogforwarders
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - clusterloggings.logging.openshift.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterloggings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - elasticsearches.logging.openshift.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - logging.openshift.io
    resources:
      - elasticsearches
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - kibanas.logging.openshift.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - logging.openshift.io
    resources:
      - kibanas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - packages.operators.coreos.com
    resources:
      - packagemanifests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreamimages
      - imagestreammappings
      - imagestreams
      - imagestreamtags
      - imagetags
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams/layers
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
      - project.openshift.io
    resources:
      - projects
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - persistentvolumeclaims/status
      - pods
      - replicationcontrollers
      - replicationcontrollers/scale
      - serviceaccounts
      - services
      - services/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - bindings
      - events
      - limitranges
      - namespaces/status
      - pods/log
      - pods/status
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/scale
      - deployments/status
      - replicasets
      - replicasets/scale
      - replicasets/status
      - statefulsets
      - statefulsets/scale
      - statefulsets/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
      - horizontalpodautoscalers/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - cronjobs/status
      - jobs
      - jobs/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/scale
      - deployments/status
      - ingresses
      - ingresses/status
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicasets/status
      - replicationcontrollers/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
      - poddisruptionbudgets/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingresses/status
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - buildconfigs
      - buildconfigs/webhooks
      - builds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - builds/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - build.openshift.io
    resources:
      - jenkins
    verbs:
      - view
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs
      - deploymentconfigs/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs/log
      - deploymentconfigs/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - quota.openshift.io
    resources:
      - appliedclusterresourcequotas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - template.openshift.io
    resources:
      - processedtemplates
      - templateconfigs
      - templateinstances
      - templates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - buildlogs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - resourcequotausages
    verbs:
      - get
      - list
      - watch
