apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-chartrepos-viewer
rules:
  - apiGroups:
      - helm.openshift.io
    resources:
      - helmchartrepositories
    verbs:
      - get
      - list
