apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.opgroup.permissions/aggregate-to-9337dac30a6def29-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: kibanas.logging.openshift.io-v1-edit
rules:
  - apiGroups:
      - logging.openshift.io
    resources:
      - kibanas
    verbs:
      - create
      - update
      - patch
      - delete
