apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  name: operatorhub-config-reader
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - operatorhubs
    verbs:
      - get
      - list
      - watch
