apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-operator
rules:
  - apiGroups:
      - oauth.openshift.io
    resourceNames:
      - console
    resources:
      - oauthclients
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - oauths
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - proxies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - consoles
      - consoles/status
      - clusteroperators
      - clusteroperators/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - operator.openshift.io
    resources:
      - consoles
      - consoles/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - console.openshift.io
    resources:
      - consoleclidownloads
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
