aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        olm.opgroup.permissions/aggregate-to-398cc1f7861443fe-edit: "true"
    - matchLabels:
        olm.opgroup.permissions/aggregate-to-1b4d744dedc664d9-edit: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.owner: openshift-logging-6hbn8
    olm.owner.kind: OperatorGroup
    olm.owner.namespace: openshift-logging
  name: openshift-logging-6hbn8-edit
rules:
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterloggings
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterlogforwarders
    verbs:
      - create
      - update
      - patch
      - delete
