apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.opgroup.permissions/aggregate-to-4bca9f23e412d79d-view: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: packagemanifests-v1-view
rules:
  - apiGroups:
      - packages.operators.coreos.com
    resources:
      - packagemanifests
    verbs:
      - get
      - list
      - watch
