apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.opgroup.permissions/aggregate-to-398cc1f7861443fe-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: clusterloggings.logging.openshift.io-v1-admin
rules:
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterloggings
    verbs:
      - '*'
