apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.opgroup.permissions/aggregate-to-e43efcaa45c9f8d0-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: elasticsearches.logging.openshift.io-v1-admin
rules:
  - apiGroups:
      - logging.openshift.io
    resources:
      - elasticsearches
    verbs:
      - '*'
