apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-api-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: machine-api-operator
subjects:
  - kind: ServiceAccount
    name: machine-api-operator
    namespace: openshift-machine-api
