apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: marketplace-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: marketplace-operator
subjects:
  - kind: ServiceAccount
    name: marketplace-operator
    namespace: openshift-marketplace
