apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:node-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:master
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-apiserver
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:node-admins
