aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        authorization.openshift.io/aggregate-to-basic-user: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: A user that can get basic information about projects.
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: basic-user
rules:
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - user.openshift.io
    resourceNames:
      - "~"
    resources:
      - users
    verbs:
      - get
  - apiGroups:
      - ""
      - project.openshift.io
    resources:
      - projectrequests
    verbs:
      - list
  - apiGroups:
      - ""
      - authorization.openshift.io
    resources:
      - clusterroles
    verbs:
      - get
      - list
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
  - apiGroups:
      - ""
      - project.openshift.io
    resources:
      - projects
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
      - authorization.openshift.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectaccessreviews
    verbs:
      - create
