apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: marketplace-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - operatorhubs
      - operatorhubs/status
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - operators.coreos.com
    resources:
      - catalogsources
      - operatorsources
    verbs:
      - get
      - create
      - delete
      - update
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators
      - clusteroperators/status
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
      - serviceaccounts
    verbs:
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - list
      - watch
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - get
      - update
      - list
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - delete
