apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:openshift:scc:nonroot
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - nonroot
    resources:
      - securitycontextconstraints
    verbs:
      - use
