apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  name: system:openshift:machine-config-operator:cluster-reader
rules:
  - apiGroups:
      - machineconfiguration.openshift.io
    resources:
      - containerruntimeconfigs
      - controllerconfigs
      - kubeletconfigs
      - machineconfigpools
    verbs:
      - get
      - list
      - watch
